apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: eas8qfewq-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/eas8qfewq-dotnet-basic-gitops